verb_past_tense = input("Enter a verb in past tense: ")
plural_noun = input("Enter a plural noun: ")
adverb = input("Enter a adverb: ")
verb = input("Enter a verb: ")
noun = input("Enter a noun: ")
part_of_body = input("Enter a part of the body: ")
exclamation = input("Enter a word for exclamation: ")
name_of_any_place = input("Enter a name of any place: ")

print(" PRIDE AND PREJUDICE -By Jane Austen")
print("--------------------------------------")
print("Darcy: In vain have I " + verb_past_tense + ".It will not do. My " + plural_noun + "will not be repressed.")
print("You must allow me to tell you how " + adverb + " I admire and " + verb + " you . ")
print("Elizabeth: If you were less of a/an " + noun + ", I would thank you .")
print("As it is,I'm sorry for causing your " + part_of_body + " to love me though your " + part_of_body + " doesnt wish to ")
print("Darcy: " + exclamation + " ! No beating around the " + noun + " with you!Might I ask why you so easily toss me ")
print("away like yesterday's " + noun + " ?")
print("Elizabeth: I could never " + verb + " a man whose responsible for ruining the " + noun + " of a most beloved sister!")
print("Darcy: My " + plural_noun + " are heavy , indeed !")
print("Elizabeth: You could never have asked for my " + part_of_body + " in marriage in any possible way that would ")
print("have tempted me to accept . You are the last " + noun + " in (the) " + name_of_any_place + " whom I could ever be")
print("prevailed upon to marry ! ")

